#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login_check


app_lucky_number:
  path: /lucky/number
  controller: App\Controller\LuckyController::number

