#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login_check:
  path: /api/login_check
  methods: POST

register:
  path: /register
  controller: App\Controller\DefaultController::register
  methods: POST

addArticles:
  path: /addArticles
  controller: App\Controller\DefaultController::addArticles
  methods: POST

api:
  path: /api
  controller: App\Controller\DefaultController::api

